version: 0.2

phases:
  install:
    commands:
      - echo "========== INSTALL PHASE =========="

  build:
    commands:
      - echo "========== BUILD STAGE =========="
      - ls
      - echo "Raw source version: $CODEBUILD_SOURCE_VERSION"
      - BRANCH_NAME=$(echo $CODEBUILD_SOURCE_VERSION | cut -d'/' -f3)
      - echo "Build Stage Branch Name: $BRANCH_NAME"
      - echo "=================================="

  post_build:
    commands:
      - echo "========== TEST STAGE =========="
      - ls
      - BRANCH_NAME=$(echo $CODEBUILD_SOURCE_VERSION | cut -d'/' -f3)
      - echo "Test Stage Branch Name: $BRANCH_NAME"
      - echo "================================="

  finally:
    commands:
      - echo "========== DEPLOY STAGE =========="
      - ls
      - BRANCH_NAME=$(echo $CODEBUILD_SOURCE_VERSION | cut -d'/' -f3)
      - echo "Deploy Stage Branch Name: $BRANCH_NAME"
      - echo "===================================="